cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
   name: bee  
   labels:
     tier: db
spec:
  containers:
  - name: bee
    image: nginx
  tolerations:
  - key: "spray" 
    operator: "Equal" 
    value: "mortein" 
    effect: "NoExecute"
    tolerationSeconds: 3600
EOF